<a href="https://colab.research.google.com/github/vidhirawat10/YBI/blob/main/Women_Cloth_Reviews_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**WOMEN CLOTH REVIEWS PREDICTION WITH MULTI NOMIAL NAIVE BAYES**

**OBJECTIVE** - The objective of the project is to develop a machine learning model that can accurately predict the sentiment of reviews (positive or negative) for women's clothing. By analyzing the text of these reviews using a Multinomial Naive Bayes algorithm, the model aims to classify new reviews based on their sentiment, helping businesses understand customer opinions and improve their products and services.

**DATA SOURCE** - YBI Foundation Github's dataset

**1. Importing Libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**2. Importing Dataset**

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/YBIFoundation/ProjectHub-MachineLearning/main/Women%20Clothing%20E-Commerce%20Review.csv")

**3. Describing Data - Data Visualization**

In [ ]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [ ]:
df.shape

(23486, 10)

**4. Data Preprocessing**

In [ ]:
df.isna().sum()  #checking if any null value present in dataset or not

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [ ]:
df[df['Review']==""] = np.NaN     #Filling missing values in the Review column with the value No review is given.
df['Review'].fillna("No review is given", inplace=True)
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [ ]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

**5. Defining Target Variable (y) and Feature Variables (X)**

In [ ]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [ ]:
X = df['Review']
y = df['Review']
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

**6. Train Test Split**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=  0.7, random_state = 2529)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

**7. Modeling**

Getting Tokens from Feature Text

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(lowercase = True, analyzer='word', ngram_range=(2, 3), stop_words = 'english', max_features = 5000)

In [ ]:
X_train = cv.fit_transform(X_train)
cv.get_feature_names_out()

array(['00 petite', '0p fit', '10 12', ..., 'yellow color',
       'yesterday store', 'yoga pants'], dtype=object)

In [ ]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_test = cv.fit_transform(X_test)

In [ ]:
cv.get_feature_names_out()

array(['00p 0p', '10 12', '10 bought', ..., 'years old', 'yoga pants',
       'yr old'], dtype=object)

In [ ]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

**8. Model Train**

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

**Model Prediction**

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred.shape

(7046,)

In [ ]:
y_pred

array(['No review is given', 'No review is given', 'No review is given',
       ..., 'No review is given', 'No review is given',
       'No review is given'], dtype='<U508')

Probaility of Each Predicted Class

In [ ]:
model.predict_proba(X_test)

array([[6.13487812e-05, 6.11775698e-05, 6.20387784e-05, ...,
        6.15205062e-05, 6.22125738e-05, 6.25617314e-05],
       [6.14114249e-05, 6.13256719e-05, 6.17558101e-05, ...,
        6.14973150e-05, 6.18422510e-05, 6.20155478e-05],
       [6.16815626e-05, 6.15462690e-05, 6.22259901e-05, ...,
        6.18171806e-05, 6.23629146e-05, 6.26377507e-05],
       ...,
       [6.10811231e-05, 6.09106586e-05, 6.17681099e-05, ...,
        6.12520989e-05, 6.19411470e-05, 6.22887813e-05],
       [6.14189210e-05, 6.12964384e-05, 6.19115506e-05, ...,
        6.15416729e-05, 6.20353860e-05, 6.22838751e-05],
       [6.09168631e-05, 6.08925474e-05, 6.10142716e-05, ...,
        6.09411934e-05, 6.10386603e-05, 6.10874814e-05]])

**Model Evaluation**

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
print(classification_report(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              precision    recall  f1-score   support

                                                                                                                                                                                                                                                             -i normally don't go for these tops because with my hourglass frame and wider hips, it only makes me look wider. however, like others, i was drawn to the fabric and feel.the bottom half really is 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Recategories Ratings as Poor(0) and Good (1)

In [ ]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

Re-rating as 1,2,3 as 0 and 4,5 as 1

In [ ]:
df.replace({'Rating' : { 1 : 0, 2 : 0, 3 : 0, 4 : 1, 5 : 1}}, inplace = True)

In [ ]:
y = df['Rating']
x = df['Review']

**Train Test Split**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=2529)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

Getting Tokens from Feature Text

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2, 3), stop_words='english', max_features=50000)
X_train = cv.fit_transform(X_train)
X_test = cv.fit_transform(X_test)

Model re-training

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

**8. Model prediction**

In [ ]:
y_pred = model.predict(X_test)
y_pred.shape

(7046,)

In [ ]:
y_pred

array([1, 0, 1, ..., 0, 1, 1])

**9. Model evaluation**

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))

[[ 741  789]
 [2655 2861]]


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.22      0.48      0.30      1530
           1       0.78      0.52      0.62      5516

    accuracy                           0.51      7046
   macro avg       0.50      0.50      0.46      7046
weighted avg       0.66      0.51      0.55      7046



**Explaination** - This project is all about creating a model that can make predictions. First, I got all the necessary libraries and a test dataset. I looked over the dataset and cleaned it up to get it ready. Then, I saved part of it for testing and used the rest to train the model. After that, I used the model to make some predictions. Finally, I checked how accurate the predictions were with the test data, made some adjustments, and re-trained the model to improve its accuracy.